# Generated by Django 3.1.2 on 2020-10-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20201003_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='download_key',
            field=models.CharField(default='asdfasdf', max_length=150),
            preserve_default=False,
        ),
    ]
